-- =============================================================
-- Migration v16: Timesheet compliance view (HR + line managers)
--
-- HR and line managers get emailed a daily reminder digest, but had no
-- way to come back and look at the same picture on their own terms. This
-- adds the query behind an in-app "Compliance" tab.
--
-- The hard part is that 'missing' is not a row. approved/rejected/pending
-- are timesheets.status values you can filter with a WHERE; 'missing' is
-- the ABSENCE of a row on a day the employee was expected to work, so it
-- has to be generated (working-day calendar, joining date, approved
-- full-day leave) and then subtracted from. That logic already existed
-- inside timesheet_status_report() for the reminder job — rather than
-- copy it, (a) below extracts it so both callers share one definition.
-- The reminder emails and the UI disagreeing about who is missing would
-- be worse than either being wrong on its own.
--
--   (a) owes_timesheet(emp, date) — the single source of truth for "did
--       this person owe a sheet on this day", extracted from
--       timesheet_status_report()'s problem_days CTE.
--   (b) timesheet_compliance(from, to) — one row per employee-day across
--       all four states, SELF-SCOPING by the caller's role. There is no
--       scope parameter, so a line manager cannot widen their view by
--       tampering with the request:
--         HR (hr_view_timesheets) / IT -> every employee in their own
--             visible offices (same rule RLS already applies elsewhere)
--         manager / c_suite           -> only their direct reports
--         anyone else                 -> only themselves
--   (c) timesheet_status_report() refactored onto the shared helper.
--
-- Idempotent — safe to re-run.
-- =============================================================

BEGIN;

-- ── (a) Did this employee owe a timesheet on this date? ────────────
-- Deliberately NOT security-sensitive on its own: it answers a question
-- about working days, not about timesheet contents. It is SECURITY
-- DEFINER only because is_working_day() and leave_requests are behind
-- RLS. See SECURITY_BACKLOG.txt LOW-2 — like the other calendar helpers
-- it takes an arbitrary employee id, so it is revoked from PUBLIC below
-- and reached only through the two functions that wrap it.
CREATE OR REPLACE FUNCTION public.owes_timesheet(p_emp UUID, p_date DATE)
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.is_working_day(p_emp, p_date)
    -- Only a full-day approved leave excuses the day — someone on two
    -- hours' hourly leave still worked the rest and still owes a sheet.
    AND NOT EXISTS (
      SELECT 1 FROM public.leave_requests lr
      WHERE lr.employee_id = p_emp
        AND lr.status = 'approved' AND lr.revoked_at IS NULL
        AND lr.unit = 'daily'
        AND p_date BETWEEN lr.start_date AND lr.end_date
    );
$$;

REVOKE EXECUTE ON FUNCTION public.owes_timesheet(UUID, DATE) FROM PUBLIC;

-- ── (b) The compliance view ────────────────────────────────────────
-- p_from/p_to are REQUIRED and hard-capped: unlike real timesheet rows,
-- 'missing' days are generated by generate_series, so an unbounded range
-- would produce headcount x days rows and melt the browser. 92 days is a
-- generous quarter.
CREATE OR REPLACE FUNCTION public.timesheet_compliance(p_from DATE, p_to DATE)
RETURNS TABLE (
  employee_id  UUID,
  full_name    TEXT,
  email        TEXT,
  office_id    UUID,
  office_name  TEXT,
  work_date    DATE,
  state        TEXT,
  is_late      BOOLEAN,
  timesheet_id UUID,
  total_hours  NUMERIC,
  submitted_at TIMESTAMPTZ
) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_uid     UUID := auth.uid();
  v_is_hr   BOOLEAN;
  v_is_mgr  BOOLEAN;
  v_offices UUID[];
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated.'; END IF;
  IF p_from IS NULL OR p_to IS NULL THEN RAISE EXCEPTION 'A date range is required.'; END IF;
  IF p_to < p_from THEN RAISE EXCEPTION 'End date is before start date.'; END IF;
  IF p_to - p_from > 92 THEN RAISE EXCEPTION 'Date range cannot exceed 92 days.'; END IF;

  v_is_hr  := public.my_has_role('hr_view_timesheets') OR public.my_has_role('it');
  v_is_mgr := public.my_has_role('manager') OR public.my_has_role('c_suite');
  v_offices := public.visible_office_ids_for(v_uid);

  RETURN QUERY
  WITH scoped_employees AS (
    SELECT p.id, p.full_name, p.email, p.office_id, p.joining_date,
           o.name AS office_name, o.timezone, o.timesheet_deadline
    FROM public.profiles p
    JOIN public.offices o ON o.id = p.office_id
    WHERE p.onboarding_complete
      AND p.joining_date IS NOT NULL
      AND o.is_active
      AND (
        -- HR/IT: everyone in the offices they can already see.
        (v_is_hr AND p.office_id = ANY(v_offices))
        -- Manager/C-suite: their own reports only, still office-bounded
        -- so it can never exceed what profiles_read_subordinates allows.
        OR (v_is_mgr AND v_uid = ANY(p.manager_ids) AND p.office_id = ANY(v_offices))
        -- Everyone else (and HR/managers looking at their own row).
        OR p.id = v_uid
      )
  ),
  candidate_days AS (
    -- Never generate days before someone joined, so a new starter isn't
    -- reported 'missing' for a period they didn't work here.
    SELECT se.*, gs.d::date AS d
    FROM scoped_employees se
    CROSS JOIN LATERAL generate_series(
      GREATEST(p_from, se.joining_date), p_to, INTERVAL '1 day'
    ) AS gs(d)
  ),
  owed AS (
    SELECT cd.* FROM candidate_days cd
    WHERE public.owes_timesheet(cd.id, cd.d)
  ),
  live AS (
    -- The employee's sheet for that day. A rejected sheet is superseded
    -- by a later resubmission for the same date, so prefer a
    -- pending/approved row and fall back to the most recent rejection.
    SELECT ow.*, cur.id AS ts_id, cur.status::text AS ts_status,
           cur.total_hours AS ts_hours, cur.created_at AS ts_created
    FROM owed ow
    LEFT JOIN LATERAL (
      SELECT ts.* FROM public.timesheets ts
      WHERE ts.employee_id = ow.id AND ts.date = ow.d
      ORDER BY (ts.status IN ('pending','approved')) DESC, ts.created_at DESC
      LIMIT 1
    ) cur ON true
  )
  SELECT
    l.id, l.full_name, l.email, l.office_id, l.office_name, l.d,
    COALESCE(l.ts_status, 'missing'),
    -- 'late' is a badge, not a state: a late sheet is still approved.
    -- NULL rather than false when there is no sheet at all, so the UI can
    -- tell "on time" apart from "not applicable".
    CASE WHEN l.ts_created IS NULL THEN NULL
         ELSE (l.ts_created AT TIME ZONE l.timezone) > (l.d + l.timesheet_deadline)
    END,
    l.ts_id, l.ts_hours, l.ts_created
  FROM live l
  ORDER BY l.d DESC, l.full_name;
END;
$$;

-- Intentionally left callable by `authenticated`: the function derives
-- its entire scope from auth.uid() internally and returns nothing useful
-- to an unauthenticated caller (it raises). This is the opposite of
-- timesheet_status_report(), which takes no caller context and therefore
-- had to be locked to service_role.

-- ── (c) Point the reminder job at the same shared helper ───────────
-- Same rules as before, now expressed once. The joining_date /
-- onboarding_complete prefilters stay in candidate_days as an
-- optimisation (they cut the generate_series fan-out before the
-- per-row helper is called at all).
CREATE OR REPLACE FUNCTION public.timesheet_status_report(p_backlog_days INT DEFAULT 14)
RETURNS TABLE (
  employee_id   UUID,
  full_name     TEXT,
  email         TEXT,
  office_id     UUID,
  office_name   TEXT,
  manager_ids   UUID[],
  business_date DATE,
  state         TEXT
) LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  WITH windows AS (
    SELECT o.id AS office_id, o.name AS office_name, o.timezone, o.timesheet_deadline,
           ((now() AT TIME ZONE o.timezone)::date - 1) AS business_date
    FROM public.offices o
    WHERE o.is_active
  ),
  candidate_days AS (
    SELECT p.id AS employee_id, p.full_name, p.email, p.office_id,
           w.office_name, p.manager_ids, w.timezone, w.timesheet_deadline, w.business_date,
           gs.d::date AS d
    FROM public.profiles p
    JOIN windows w ON w.office_id = p.office_id
    CROSS JOIN LATERAL generate_series(
      w.business_date - p_backlog_days, w.business_date, INTERVAL '1 day'
    ) AS gs(d)
    WHERE p.onboarding_complete
      AND p.joining_date IS NOT NULL
      AND p.joining_date <= gs.d::date
  ),
  problem_days AS (
    SELECT cd.*,
      (SELECT t.created_at FROM public.timesheets t
        WHERE t.employee_id = cd.employee_id AND t.date = cd.d
          AND t.status IN ('pending', 'approved')
        LIMIT 1) AS live_created_at
    FROM candidate_days cd
    WHERE public.owes_timesheet(cd.employee_id, cd.d)
  )
  SELECT employee_id, full_name, email, office_id, office_name, manager_ids, d, 'missing'
  FROM problem_days
  WHERE live_created_at IS NULL

  UNION ALL

  SELECT employee_id, full_name, email, office_id, office_name, manager_ids, d, 'late'
  FROM problem_days
  WHERE live_created_at IS NOT NULL
    AND d = business_date
    AND (live_created_at AT TIME ZONE timezone) > (d + timesheet_deadline);
$$;

-- CREATE OR REPLACE resets grants to the default (EXECUTE to PUBLIC), so
-- the v13 revoke has to be reapplied here or replacing the function would
-- silently re-open the cross-office data leak it closed.
REVOKE EXECUTE ON FUNCTION public.timesheet_status_report(INT) FROM PUBLIC;

-- ── Verify before continuing ─────────────────────────────────────────
DO $$
DECLARE v_bad TEXT := '';
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_proc p
    LEFT JOIN LATERAL unnest(p.proacl) AS a(acl) ON true
    WHERE p.oid = 'public.timesheet_status_report(INT)'::regprocedure
      AND (p.proacl IS NULL OR a.acl::text LIKE '=%')
  ) THEN v_bad := v_bad || ' timesheet_status_report-still-public'; END IF;

  IF EXISTS (
    SELECT 1 FROM pg_proc p
    LEFT JOIN LATERAL unnest(p.proacl) AS a(acl) ON true
    WHERE p.oid = 'public.owes_timesheet(UUID, DATE)'::regprocedure
      AND (p.proacl IS NULL OR a.acl::text LIKE '=%')
  ) THEN v_bad := v_bad || ' owes_timesheet-still-public'; END IF;

  IF v_bad <> '' THEN RAISE EXCEPTION 'v16 verification failed:%', v_bad; END IF;
END $$;

COMMIT;
